name: "Build and Cache"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          sandbox = false
    
    - uses: cachix/cachix-action@v14
      with:
        name: claude-code
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Build claude-code
      run: |
        nix build .#claude-code
        nix build .#claude-code --json | jq -r '.[].outputs.out' | cachix push claude-code
    
    - name: Test claude-code
      run: |
        ./result/bin/claude --version