name: Test Pull Request

on:
  pull_request:
    paths:
      - 'package.nix'
      - 'flake.nix'
      - 'flake.lock'

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nix cache
        uses: cachix/cachix-action@v14
        with:
          name: nix-community
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Build package
        run: |
          nix build .#claude-code --print-build-logs
          
      - name: Test claude version
        run: |
          # Test that claude runs and reports version
          ./result/bin/claude --version
          
      - name: Verify package contents
        run: |
          # Verify the binary exists
          test -f ./result/bin/claude
          
          # Verify Node modules are installed
          test -d ./result/lib/node_modules/@anthropic-ai/claude-code
          
      - name: Run basic functionality test
        run: |
          # Test help command
          ./result/bin/claude --help || true
          
          # Verify it's using the correct Node.js version
          ./result/bin/claude --version 2>&1 | grep -E "claude-code|Claude"