name: Update Claude Code Version

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq nix

      - name: Fetch latest Claude Code version and tarball
        id: fetch
        run: |
          PACKAGE="@anthropic-ai/claude-code"
          META=$(curl -s "https://registry.npmjs.org/${PACKAGE}")
          VERSION=$(echo "$META" | jq -r '.["dist-tags"].latest')
          URL=$(echo "$META" | jq -r ".versions[\"$VERSION\"].dist.tarball")
          FILE="claude-code.tgz"
          curl -sL "$URL" -o "$FILE"
          SHA256=$(nix --extra-experimental-features nix-command hash file --type sha256 --base32 "$FILE")

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "URL=$URL" >> $GITHUB_OUTPUT
          echo "SHA256=$SHA256" >> $GITHUB_OUTPUT

      - name: Update Nix expression
        run: |
          sed -i "s|version = \".*\";|version = \"${{ steps.fetch.outputs.VERSION }}\";|" package.nix
          sed -i "s|url = \".*\";|url = \"${{ steps.fetch.outputs.URL }}\";|" package.nix
          sed -i "s|sha256 = \".*\";|sha256 = \"${{ steps.fetch.outputs.SHA256 }}\";|" package.nix

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'claude-code.nix'
          message: "chore: update Claude Code to ${{ steps.fetch.outputs.VERSION }}"

